blank_issues_enabled: false
contact_links:
  - name: "Dunia Yetu"
    url: ""
    about: "Please ask and answer questions here."
  - name: "StableNodes Security Bug Bounty"
    url: "devops@nedapay.xyz"
    about: "Please report security vulnerabilities here."
