// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NEDA-LABS/stablenode/ent/paymentorder"
	"github.com/NEDA-LABS/stablenode/ent/predicate"
	"github.com/NEDA-LABS/stablenode/ent/receiveaddress"
	"github.com/google/uuid"
)

// ReceiveAddressUpdate is the builder for updating ReceiveAddress entities.
type ReceiveAddressUpdate struct {
	config
	hooks    []Hook
	mutation *ReceiveAddressMutation
}

// Where appends a list predicates to the ReceiveAddressUpdate builder.
func (rau *ReceiveAddressUpdate) Where(ps ...predicate.ReceiveAddress) *ReceiveAddressUpdate {
	rau.mutation.Where(ps...)
	return rau
}

// SetUpdatedAt sets the "updated_at" field.
func (rau *ReceiveAddressUpdate) SetUpdatedAt(t time.Time) *ReceiveAddressUpdate {
	rau.mutation.SetUpdatedAt(t)
	return rau
}

// SetAddress sets the "address" field.
func (rau *ReceiveAddressUpdate) SetAddress(s string) *ReceiveAddressUpdate {
	rau.mutation.SetAddress(s)
	return rau
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableAddress(s *string) *ReceiveAddressUpdate {
	if s != nil {
		rau.SetAddress(*s)
	}
	return rau
}

// SetSalt sets the "salt" field.
func (rau *ReceiveAddressUpdate) SetSalt(b []byte) *ReceiveAddressUpdate {
	rau.mutation.SetSalt(b)
	return rau
}

// ClearSalt clears the value of the "salt" field.
func (rau *ReceiveAddressUpdate) ClearSalt() *ReceiveAddressUpdate {
	rau.mutation.ClearSalt()
	return rau
}

// SetStatus sets the "status" field.
func (rau *ReceiveAddressUpdate) SetStatus(r receiveaddress.Status) *ReceiveAddressUpdate {
	rau.mutation.SetStatus(r)
	return rau
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableStatus(r *receiveaddress.Status) *ReceiveAddressUpdate {
	if r != nil {
		rau.SetStatus(*r)
	}
	return rau
}

// SetIsDeployed sets the "is_deployed" field.
func (rau *ReceiveAddressUpdate) SetIsDeployed(b bool) *ReceiveAddressUpdate {
	rau.mutation.SetIsDeployed(b)
	return rau
}

// SetNillableIsDeployed sets the "is_deployed" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableIsDeployed(b *bool) *ReceiveAddressUpdate {
	if b != nil {
		rau.SetIsDeployed(*b)
	}
	return rau
}

// SetDeploymentBlock sets the "deployment_block" field.
func (rau *ReceiveAddressUpdate) SetDeploymentBlock(i int64) *ReceiveAddressUpdate {
	rau.mutation.ResetDeploymentBlock()
	rau.mutation.SetDeploymentBlock(i)
	return rau
}

// SetNillableDeploymentBlock sets the "deployment_block" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableDeploymentBlock(i *int64) *ReceiveAddressUpdate {
	if i != nil {
		rau.SetDeploymentBlock(*i)
	}
	return rau
}

// AddDeploymentBlock adds i to the "deployment_block" field.
func (rau *ReceiveAddressUpdate) AddDeploymentBlock(i int64) *ReceiveAddressUpdate {
	rau.mutation.AddDeploymentBlock(i)
	return rau
}

// ClearDeploymentBlock clears the value of the "deployment_block" field.
func (rau *ReceiveAddressUpdate) ClearDeploymentBlock() *ReceiveAddressUpdate {
	rau.mutation.ClearDeploymentBlock()
	return rau
}

// SetDeploymentTxHash sets the "deployment_tx_hash" field.
func (rau *ReceiveAddressUpdate) SetDeploymentTxHash(s string) *ReceiveAddressUpdate {
	rau.mutation.SetDeploymentTxHash(s)
	return rau
}

// SetNillableDeploymentTxHash sets the "deployment_tx_hash" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableDeploymentTxHash(s *string) *ReceiveAddressUpdate {
	if s != nil {
		rau.SetDeploymentTxHash(*s)
	}
	return rau
}

// ClearDeploymentTxHash clears the value of the "deployment_tx_hash" field.
func (rau *ReceiveAddressUpdate) ClearDeploymentTxHash() *ReceiveAddressUpdate {
	rau.mutation.ClearDeploymentTxHash()
	return rau
}

// SetDeployedAt sets the "deployed_at" field.
func (rau *ReceiveAddressUpdate) SetDeployedAt(t time.Time) *ReceiveAddressUpdate {
	rau.mutation.SetDeployedAt(t)
	return rau
}

// SetNillableDeployedAt sets the "deployed_at" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableDeployedAt(t *time.Time) *ReceiveAddressUpdate {
	if t != nil {
		rau.SetDeployedAt(*t)
	}
	return rau
}

// ClearDeployedAt clears the value of the "deployed_at" field.
func (rau *ReceiveAddressUpdate) ClearDeployedAt() *ReceiveAddressUpdate {
	rau.mutation.ClearDeployedAt()
	return rau
}

// SetNetworkIdentifier sets the "network_identifier" field.
func (rau *ReceiveAddressUpdate) SetNetworkIdentifier(s string) *ReceiveAddressUpdate {
	rau.mutation.SetNetworkIdentifier(s)
	return rau
}

// SetNillableNetworkIdentifier sets the "network_identifier" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableNetworkIdentifier(s *string) *ReceiveAddressUpdate {
	if s != nil {
		rau.SetNetworkIdentifier(*s)
	}
	return rau
}

// ClearNetworkIdentifier clears the value of the "network_identifier" field.
func (rau *ReceiveAddressUpdate) ClearNetworkIdentifier() *ReceiveAddressUpdate {
	rau.mutation.ClearNetworkIdentifier()
	return rau
}

// SetChainID sets the "chain_id" field.
func (rau *ReceiveAddressUpdate) SetChainID(i int64) *ReceiveAddressUpdate {
	rau.mutation.ResetChainID()
	rau.mutation.SetChainID(i)
	return rau
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableChainID(i *int64) *ReceiveAddressUpdate {
	if i != nil {
		rau.SetChainID(*i)
	}
	return rau
}

// AddChainID adds i to the "chain_id" field.
func (rau *ReceiveAddressUpdate) AddChainID(i int64) *ReceiveAddressUpdate {
	rau.mutation.AddChainID(i)
	return rau
}

// ClearChainID clears the value of the "chain_id" field.
func (rau *ReceiveAddressUpdate) ClearChainID() *ReceiveAddressUpdate {
	rau.mutation.ClearChainID()
	return rau
}

// SetAssignedAt sets the "assigned_at" field.
func (rau *ReceiveAddressUpdate) SetAssignedAt(t time.Time) *ReceiveAddressUpdate {
	rau.mutation.SetAssignedAt(t)
	return rau
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableAssignedAt(t *time.Time) *ReceiveAddressUpdate {
	if t != nil {
		rau.SetAssignedAt(*t)
	}
	return rau
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (rau *ReceiveAddressUpdate) ClearAssignedAt() *ReceiveAddressUpdate {
	rau.mutation.ClearAssignedAt()
	return rau
}

// SetRecycledAt sets the "recycled_at" field.
func (rau *ReceiveAddressUpdate) SetRecycledAt(t time.Time) *ReceiveAddressUpdate {
	rau.mutation.SetRecycledAt(t)
	return rau
}

// SetNillableRecycledAt sets the "recycled_at" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableRecycledAt(t *time.Time) *ReceiveAddressUpdate {
	if t != nil {
		rau.SetRecycledAt(*t)
	}
	return rau
}

// ClearRecycledAt clears the value of the "recycled_at" field.
func (rau *ReceiveAddressUpdate) ClearRecycledAt() *ReceiveAddressUpdate {
	rau.mutation.ClearRecycledAt()
	return rau
}

// SetTimesUsed sets the "times_used" field.
func (rau *ReceiveAddressUpdate) SetTimesUsed(i int) *ReceiveAddressUpdate {
	rau.mutation.ResetTimesUsed()
	rau.mutation.SetTimesUsed(i)
	return rau
}

// SetNillableTimesUsed sets the "times_used" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableTimesUsed(i *int) *ReceiveAddressUpdate {
	if i != nil {
		rau.SetTimesUsed(*i)
	}
	return rau
}

// AddTimesUsed adds i to the "times_used" field.
func (rau *ReceiveAddressUpdate) AddTimesUsed(i int) *ReceiveAddressUpdate {
	rau.mutation.AddTimesUsed(i)
	return rau
}

// SetLastIndexedBlock sets the "last_indexed_block" field.
func (rau *ReceiveAddressUpdate) SetLastIndexedBlock(i int64) *ReceiveAddressUpdate {
	rau.mutation.ResetLastIndexedBlock()
	rau.mutation.SetLastIndexedBlock(i)
	return rau
}

// SetNillableLastIndexedBlock sets the "last_indexed_block" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableLastIndexedBlock(i *int64) *ReceiveAddressUpdate {
	if i != nil {
		rau.SetLastIndexedBlock(*i)
	}
	return rau
}

// AddLastIndexedBlock adds i to the "last_indexed_block" field.
func (rau *ReceiveAddressUpdate) AddLastIndexedBlock(i int64) *ReceiveAddressUpdate {
	rau.mutation.AddLastIndexedBlock(i)
	return rau
}

// ClearLastIndexedBlock clears the value of the "last_indexed_block" field.
func (rau *ReceiveAddressUpdate) ClearLastIndexedBlock() *ReceiveAddressUpdate {
	rau.mutation.ClearLastIndexedBlock()
	return rau
}

// SetLastUsed sets the "last_used" field.
func (rau *ReceiveAddressUpdate) SetLastUsed(t time.Time) *ReceiveAddressUpdate {
	rau.mutation.SetLastUsed(t)
	return rau
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableLastUsed(t *time.Time) *ReceiveAddressUpdate {
	if t != nil {
		rau.SetLastUsed(*t)
	}
	return rau
}

// ClearLastUsed clears the value of the "last_used" field.
func (rau *ReceiveAddressUpdate) ClearLastUsed() *ReceiveAddressUpdate {
	rau.mutation.ClearLastUsed()
	return rau
}

// SetTxHash sets the "tx_hash" field.
func (rau *ReceiveAddressUpdate) SetTxHash(s string) *ReceiveAddressUpdate {
	rau.mutation.SetTxHash(s)
	return rau
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableTxHash(s *string) *ReceiveAddressUpdate {
	if s != nil {
		rau.SetTxHash(*s)
	}
	return rau
}

// ClearTxHash clears the value of the "tx_hash" field.
func (rau *ReceiveAddressUpdate) ClearTxHash() *ReceiveAddressUpdate {
	rau.mutation.ClearTxHash()
	return rau
}

// SetValidUntil sets the "valid_until" field.
func (rau *ReceiveAddressUpdate) SetValidUntil(t time.Time) *ReceiveAddressUpdate {
	rau.mutation.SetValidUntil(t)
	return rau
}

// SetNillableValidUntil sets the "valid_until" field if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillableValidUntil(t *time.Time) *ReceiveAddressUpdate {
	if t != nil {
		rau.SetValidUntil(*t)
	}
	return rau
}

// ClearValidUntil clears the value of the "valid_until" field.
func (rau *ReceiveAddressUpdate) ClearValidUntil() *ReceiveAddressUpdate {
	rau.mutation.ClearValidUntil()
	return rau
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (rau *ReceiveAddressUpdate) SetPaymentOrderID(id uuid.UUID) *ReceiveAddressUpdate {
	rau.mutation.SetPaymentOrderID(id)
	return rau
}

// SetNillablePaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID if the given value is not nil.
func (rau *ReceiveAddressUpdate) SetNillablePaymentOrderID(id *uuid.UUID) *ReceiveAddressUpdate {
	if id != nil {
		rau = rau.SetPaymentOrderID(*id)
	}
	return rau
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (rau *ReceiveAddressUpdate) SetPaymentOrder(p *PaymentOrder) *ReceiveAddressUpdate {
	return rau.SetPaymentOrderID(p.ID)
}

// Mutation returns the ReceiveAddressMutation object of the builder.
func (rau *ReceiveAddressUpdate) Mutation() *ReceiveAddressMutation {
	return rau.mutation
}

// ClearPaymentOrder clears the "payment_order" edge to the PaymentOrder entity.
func (rau *ReceiveAddressUpdate) ClearPaymentOrder() *ReceiveAddressUpdate {
	rau.mutation.ClearPaymentOrder()
	return rau
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rau *ReceiveAddressUpdate) Save(ctx context.Context) (int, error) {
	rau.defaults()
	return withHooks(ctx, rau.sqlSave, rau.mutation, rau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rau *ReceiveAddressUpdate) SaveX(ctx context.Context) int {
	affected, err := rau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rau *ReceiveAddressUpdate) Exec(ctx context.Context) error {
	_, err := rau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rau *ReceiveAddressUpdate) ExecX(ctx context.Context) {
	if err := rau.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rau *ReceiveAddressUpdate) defaults() {
	if _, ok := rau.mutation.UpdatedAt(); !ok {
		v := receiveaddress.UpdateDefaultUpdatedAt()
		rau.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rau *ReceiveAddressUpdate) check() error {
	if v, ok := rau.mutation.Status(); ok {
		if err := receiveaddress.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReceiveAddress.status": %w`, err)}
		}
	}
	if v, ok := rau.mutation.DeploymentTxHash(); ok {
		if err := receiveaddress.DeploymentTxHashValidator(v); err != nil {
			return &ValidationError{Name: "deployment_tx_hash", err: fmt.Errorf(`ent: validator failed for field "ReceiveAddress.deployment_tx_hash": %w`, err)}
		}
	}
	if v, ok := rau.mutation.TxHash(); ok {
		if err := receiveaddress.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "ReceiveAddress.tx_hash": %w`, err)}
		}
	}
	return nil
}

func (rau *ReceiveAddressUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(receiveaddress.Table, receiveaddress.Columns, sqlgraph.NewFieldSpec(receiveaddress.FieldID, field.TypeInt))
	if ps := rau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rau.mutation.UpdatedAt(); ok {
		_spec.SetField(receiveaddress.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := rau.mutation.Address(); ok {
		_spec.SetField(receiveaddress.FieldAddress, field.TypeString, value)
	}
	if value, ok := rau.mutation.Salt(); ok {
		_spec.SetField(receiveaddress.FieldSalt, field.TypeBytes, value)
	}
	if rau.mutation.SaltCleared() {
		_spec.ClearField(receiveaddress.FieldSalt, field.TypeBytes)
	}
	if value, ok := rau.mutation.Status(); ok {
		_spec.SetField(receiveaddress.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := rau.mutation.IsDeployed(); ok {
		_spec.SetField(receiveaddress.FieldIsDeployed, field.TypeBool, value)
	}
	if value, ok := rau.mutation.DeploymentBlock(); ok {
		_spec.SetField(receiveaddress.FieldDeploymentBlock, field.TypeInt64, value)
	}
	if value, ok := rau.mutation.AddedDeploymentBlock(); ok {
		_spec.AddField(receiveaddress.FieldDeploymentBlock, field.TypeInt64, value)
	}
	if rau.mutation.DeploymentBlockCleared() {
		_spec.ClearField(receiveaddress.FieldDeploymentBlock, field.TypeInt64)
	}
	if value, ok := rau.mutation.DeploymentTxHash(); ok {
		_spec.SetField(receiveaddress.FieldDeploymentTxHash, field.TypeString, value)
	}
	if rau.mutation.DeploymentTxHashCleared() {
		_spec.ClearField(receiveaddress.FieldDeploymentTxHash, field.TypeString)
	}
	if value, ok := rau.mutation.DeployedAt(); ok {
		_spec.SetField(receiveaddress.FieldDeployedAt, field.TypeTime, value)
	}
	if rau.mutation.DeployedAtCleared() {
		_spec.ClearField(receiveaddress.FieldDeployedAt, field.TypeTime)
	}
	if value, ok := rau.mutation.NetworkIdentifier(); ok {
		_spec.SetField(receiveaddress.FieldNetworkIdentifier, field.TypeString, value)
	}
	if rau.mutation.NetworkIdentifierCleared() {
		_spec.ClearField(receiveaddress.FieldNetworkIdentifier, field.TypeString)
	}
	if value, ok := rau.mutation.ChainID(); ok {
		_spec.SetField(receiveaddress.FieldChainID, field.TypeInt64, value)
	}
	if value, ok := rau.mutation.AddedChainID(); ok {
		_spec.AddField(receiveaddress.FieldChainID, field.TypeInt64, value)
	}
	if rau.mutation.ChainIDCleared() {
		_spec.ClearField(receiveaddress.FieldChainID, field.TypeInt64)
	}
	if value, ok := rau.mutation.AssignedAt(); ok {
		_spec.SetField(receiveaddress.FieldAssignedAt, field.TypeTime, value)
	}
	if rau.mutation.AssignedAtCleared() {
		_spec.ClearField(receiveaddress.FieldAssignedAt, field.TypeTime)
	}
	if value, ok := rau.mutation.RecycledAt(); ok {
		_spec.SetField(receiveaddress.FieldRecycledAt, field.TypeTime, value)
	}
	if rau.mutation.RecycledAtCleared() {
		_spec.ClearField(receiveaddress.FieldRecycledAt, field.TypeTime)
	}
	if value, ok := rau.mutation.TimesUsed(); ok {
		_spec.SetField(receiveaddress.FieldTimesUsed, field.TypeInt, value)
	}
	if value, ok := rau.mutation.AddedTimesUsed(); ok {
		_spec.AddField(receiveaddress.FieldTimesUsed, field.TypeInt, value)
	}
	if value, ok := rau.mutation.LastIndexedBlock(); ok {
		_spec.SetField(receiveaddress.FieldLastIndexedBlock, field.TypeInt64, value)
	}
	if value, ok := rau.mutation.AddedLastIndexedBlock(); ok {
		_spec.AddField(receiveaddress.FieldLastIndexedBlock, field.TypeInt64, value)
	}
	if rau.mutation.LastIndexedBlockCleared() {
		_spec.ClearField(receiveaddress.FieldLastIndexedBlock, field.TypeInt64)
	}
	if value, ok := rau.mutation.LastUsed(); ok {
		_spec.SetField(receiveaddress.FieldLastUsed, field.TypeTime, value)
	}
	if rau.mutation.LastUsedCleared() {
		_spec.ClearField(receiveaddress.FieldLastUsed, field.TypeTime)
	}
	if value, ok := rau.mutation.TxHash(); ok {
		_spec.SetField(receiveaddress.FieldTxHash, field.TypeString, value)
	}
	if rau.mutation.TxHashCleared() {
		_spec.ClearField(receiveaddress.FieldTxHash, field.TypeString)
	}
	if value, ok := rau.mutation.ValidUntil(); ok {
		_spec.SetField(receiveaddress.FieldValidUntil, field.TypeTime, value)
	}
	if rau.mutation.ValidUntilCleared() {
		_spec.ClearField(receiveaddress.FieldValidUntil, field.TypeTime)
	}
	if rau.mutation.PaymentOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   receiveaddress.PaymentOrderTable,
			Columns: []string{receiveaddress.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rau.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   receiveaddress.PaymentOrderTable,
			Columns: []string{receiveaddress.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{receiveaddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rau.mutation.done = true
	return n, nil
}

// ReceiveAddressUpdateOne is the builder for updating a single ReceiveAddress entity.
type ReceiveAddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReceiveAddressMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (rauo *ReceiveAddressUpdateOne) SetUpdatedAt(t time.Time) *ReceiveAddressUpdateOne {
	rauo.mutation.SetUpdatedAt(t)
	return rauo
}

// SetAddress sets the "address" field.
func (rauo *ReceiveAddressUpdateOne) SetAddress(s string) *ReceiveAddressUpdateOne {
	rauo.mutation.SetAddress(s)
	return rauo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableAddress(s *string) *ReceiveAddressUpdateOne {
	if s != nil {
		rauo.SetAddress(*s)
	}
	return rauo
}

// SetSalt sets the "salt" field.
func (rauo *ReceiveAddressUpdateOne) SetSalt(b []byte) *ReceiveAddressUpdateOne {
	rauo.mutation.SetSalt(b)
	return rauo
}

// ClearSalt clears the value of the "salt" field.
func (rauo *ReceiveAddressUpdateOne) ClearSalt() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearSalt()
	return rauo
}

// SetStatus sets the "status" field.
func (rauo *ReceiveAddressUpdateOne) SetStatus(r receiveaddress.Status) *ReceiveAddressUpdateOne {
	rauo.mutation.SetStatus(r)
	return rauo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableStatus(r *receiveaddress.Status) *ReceiveAddressUpdateOne {
	if r != nil {
		rauo.SetStatus(*r)
	}
	return rauo
}

// SetIsDeployed sets the "is_deployed" field.
func (rauo *ReceiveAddressUpdateOne) SetIsDeployed(b bool) *ReceiveAddressUpdateOne {
	rauo.mutation.SetIsDeployed(b)
	return rauo
}

// SetNillableIsDeployed sets the "is_deployed" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableIsDeployed(b *bool) *ReceiveAddressUpdateOne {
	if b != nil {
		rauo.SetIsDeployed(*b)
	}
	return rauo
}

// SetDeploymentBlock sets the "deployment_block" field.
func (rauo *ReceiveAddressUpdateOne) SetDeploymentBlock(i int64) *ReceiveAddressUpdateOne {
	rauo.mutation.ResetDeploymentBlock()
	rauo.mutation.SetDeploymentBlock(i)
	return rauo
}

// SetNillableDeploymentBlock sets the "deployment_block" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableDeploymentBlock(i *int64) *ReceiveAddressUpdateOne {
	if i != nil {
		rauo.SetDeploymentBlock(*i)
	}
	return rauo
}

// AddDeploymentBlock adds i to the "deployment_block" field.
func (rauo *ReceiveAddressUpdateOne) AddDeploymentBlock(i int64) *ReceiveAddressUpdateOne {
	rauo.mutation.AddDeploymentBlock(i)
	return rauo
}

// ClearDeploymentBlock clears the value of the "deployment_block" field.
func (rauo *ReceiveAddressUpdateOne) ClearDeploymentBlock() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearDeploymentBlock()
	return rauo
}

// SetDeploymentTxHash sets the "deployment_tx_hash" field.
func (rauo *ReceiveAddressUpdateOne) SetDeploymentTxHash(s string) *ReceiveAddressUpdateOne {
	rauo.mutation.SetDeploymentTxHash(s)
	return rauo
}

// SetNillableDeploymentTxHash sets the "deployment_tx_hash" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableDeploymentTxHash(s *string) *ReceiveAddressUpdateOne {
	if s != nil {
		rauo.SetDeploymentTxHash(*s)
	}
	return rauo
}

// ClearDeploymentTxHash clears the value of the "deployment_tx_hash" field.
func (rauo *ReceiveAddressUpdateOne) ClearDeploymentTxHash() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearDeploymentTxHash()
	return rauo
}

// SetDeployedAt sets the "deployed_at" field.
func (rauo *ReceiveAddressUpdateOne) SetDeployedAt(t time.Time) *ReceiveAddressUpdateOne {
	rauo.mutation.SetDeployedAt(t)
	return rauo
}

// SetNillableDeployedAt sets the "deployed_at" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableDeployedAt(t *time.Time) *ReceiveAddressUpdateOne {
	if t != nil {
		rauo.SetDeployedAt(*t)
	}
	return rauo
}

// ClearDeployedAt clears the value of the "deployed_at" field.
func (rauo *ReceiveAddressUpdateOne) ClearDeployedAt() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearDeployedAt()
	return rauo
}

// SetNetworkIdentifier sets the "network_identifier" field.
func (rauo *ReceiveAddressUpdateOne) SetNetworkIdentifier(s string) *ReceiveAddressUpdateOne {
	rauo.mutation.SetNetworkIdentifier(s)
	return rauo
}

// SetNillableNetworkIdentifier sets the "network_identifier" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableNetworkIdentifier(s *string) *ReceiveAddressUpdateOne {
	if s != nil {
		rauo.SetNetworkIdentifier(*s)
	}
	return rauo
}

// ClearNetworkIdentifier clears the value of the "network_identifier" field.
func (rauo *ReceiveAddressUpdateOne) ClearNetworkIdentifier() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearNetworkIdentifier()
	return rauo
}

// SetChainID sets the "chain_id" field.
func (rauo *ReceiveAddressUpdateOne) SetChainID(i int64) *ReceiveAddressUpdateOne {
	rauo.mutation.ResetChainID()
	rauo.mutation.SetChainID(i)
	return rauo
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableChainID(i *int64) *ReceiveAddressUpdateOne {
	if i != nil {
		rauo.SetChainID(*i)
	}
	return rauo
}

// AddChainID adds i to the "chain_id" field.
func (rauo *ReceiveAddressUpdateOne) AddChainID(i int64) *ReceiveAddressUpdateOne {
	rauo.mutation.AddChainID(i)
	return rauo
}

// ClearChainID clears the value of the "chain_id" field.
func (rauo *ReceiveAddressUpdateOne) ClearChainID() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearChainID()
	return rauo
}

// SetAssignedAt sets the "assigned_at" field.
func (rauo *ReceiveAddressUpdateOne) SetAssignedAt(t time.Time) *ReceiveAddressUpdateOne {
	rauo.mutation.SetAssignedAt(t)
	return rauo
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableAssignedAt(t *time.Time) *ReceiveAddressUpdateOne {
	if t != nil {
		rauo.SetAssignedAt(*t)
	}
	return rauo
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (rauo *ReceiveAddressUpdateOne) ClearAssignedAt() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearAssignedAt()
	return rauo
}

// SetRecycledAt sets the "recycled_at" field.
func (rauo *ReceiveAddressUpdateOne) SetRecycledAt(t time.Time) *ReceiveAddressUpdateOne {
	rauo.mutation.SetRecycledAt(t)
	return rauo
}

// SetNillableRecycledAt sets the "recycled_at" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableRecycledAt(t *time.Time) *ReceiveAddressUpdateOne {
	if t != nil {
		rauo.SetRecycledAt(*t)
	}
	return rauo
}

// ClearRecycledAt clears the value of the "recycled_at" field.
func (rauo *ReceiveAddressUpdateOne) ClearRecycledAt() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearRecycledAt()
	return rauo
}

// SetTimesUsed sets the "times_used" field.
func (rauo *ReceiveAddressUpdateOne) SetTimesUsed(i int) *ReceiveAddressUpdateOne {
	rauo.mutation.ResetTimesUsed()
	rauo.mutation.SetTimesUsed(i)
	return rauo
}

// SetNillableTimesUsed sets the "times_used" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableTimesUsed(i *int) *ReceiveAddressUpdateOne {
	if i != nil {
		rauo.SetTimesUsed(*i)
	}
	return rauo
}

// AddTimesUsed adds i to the "times_used" field.
func (rauo *ReceiveAddressUpdateOne) AddTimesUsed(i int) *ReceiveAddressUpdateOne {
	rauo.mutation.AddTimesUsed(i)
	return rauo
}

// SetLastIndexedBlock sets the "last_indexed_block" field.
func (rauo *ReceiveAddressUpdateOne) SetLastIndexedBlock(i int64) *ReceiveAddressUpdateOne {
	rauo.mutation.ResetLastIndexedBlock()
	rauo.mutation.SetLastIndexedBlock(i)
	return rauo
}

// SetNillableLastIndexedBlock sets the "last_indexed_block" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableLastIndexedBlock(i *int64) *ReceiveAddressUpdateOne {
	if i != nil {
		rauo.SetLastIndexedBlock(*i)
	}
	return rauo
}

// AddLastIndexedBlock adds i to the "last_indexed_block" field.
func (rauo *ReceiveAddressUpdateOne) AddLastIndexedBlock(i int64) *ReceiveAddressUpdateOne {
	rauo.mutation.AddLastIndexedBlock(i)
	return rauo
}

// ClearLastIndexedBlock clears the value of the "last_indexed_block" field.
func (rauo *ReceiveAddressUpdateOne) ClearLastIndexedBlock() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearLastIndexedBlock()
	return rauo
}

// SetLastUsed sets the "last_used" field.
func (rauo *ReceiveAddressUpdateOne) SetLastUsed(t time.Time) *ReceiveAddressUpdateOne {
	rauo.mutation.SetLastUsed(t)
	return rauo
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableLastUsed(t *time.Time) *ReceiveAddressUpdateOne {
	if t != nil {
		rauo.SetLastUsed(*t)
	}
	return rauo
}

// ClearLastUsed clears the value of the "last_used" field.
func (rauo *ReceiveAddressUpdateOne) ClearLastUsed() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearLastUsed()
	return rauo
}

// SetTxHash sets the "tx_hash" field.
func (rauo *ReceiveAddressUpdateOne) SetTxHash(s string) *ReceiveAddressUpdateOne {
	rauo.mutation.SetTxHash(s)
	return rauo
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableTxHash(s *string) *ReceiveAddressUpdateOne {
	if s != nil {
		rauo.SetTxHash(*s)
	}
	return rauo
}

// ClearTxHash clears the value of the "tx_hash" field.
func (rauo *ReceiveAddressUpdateOne) ClearTxHash() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearTxHash()
	return rauo
}

// SetValidUntil sets the "valid_until" field.
func (rauo *ReceiveAddressUpdateOne) SetValidUntil(t time.Time) *ReceiveAddressUpdateOne {
	rauo.mutation.SetValidUntil(t)
	return rauo
}

// SetNillableValidUntil sets the "valid_until" field if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillableValidUntil(t *time.Time) *ReceiveAddressUpdateOne {
	if t != nil {
		rauo.SetValidUntil(*t)
	}
	return rauo
}

// ClearValidUntil clears the value of the "valid_until" field.
func (rauo *ReceiveAddressUpdateOne) ClearValidUntil() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearValidUntil()
	return rauo
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (rauo *ReceiveAddressUpdateOne) SetPaymentOrderID(id uuid.UUID) *ReceiveAddressUpdateOne {
	rauo.mutation.SetPaymentOrderID(id)
	return rauo
}

// SetNillablePaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID if the given value is not nil.
func (rauo *ReceiveAddressUpdateOne) SetNillablePaymentOrderID(id *uuid.UUID) *ReceiveAddressUpdateOne {
	if id != nil {
		rauo = rauo.SetPaymentOrderID(*id)
	}
	return rauo
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (rauo *ReceiveAddressUpdateOne) SetPaymentOrder(p *PaymentOrder) *ReceiveAddressUpdateOne {
	return rauo.SetPaymentOrderID(p.ID)
}

// Mutation returns the ReceiveAddressMutation object of the builder.
func (rauo *ReceiveAddressUpdateOne) Mutation() *ReceiveAddressMutation {
	return rauo.mutation
}

// ClearPaymentOrder clears the "payment_order" edge to the PaymentOrder entity.
func (rauo *ReceiveAddressUpdateOne) ClearPaymentOrder() *ReceiveAddressUpdateOne {
	rauo.mutation.ClearPaymentOrder()
	return rauo
}

// Where appends a list predicates to the ReceiveAddressUpdate builder.
func (rauo *ReceiveAddressUpdateOne) Where(ps ...predicate.ReceiveAddress) *ReceiveAddressUpdateOne {
	rauo.mutation.Where(ps...)
	return rauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rauo *ReceiveAddressUpdateOne) Select(field string, fields ...string) *ReceiveAddressUpdateOne {
	rauo.fields = append([]string{field}, fields...)
	return rauo
}

// Save executes the query and returns the updated ReceiveAddress entity.
func (rauo *ReceiveAddressUpdateOne) Save(ctx context.Context) (*ReceiveAddress, error) {
	rauo.defaults()
	return withHooks(ctx, rauo.sqlSave, rauo.mutation, rauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rauo *ReceiveAddressUpdateOne) SaveX(ctx context.Context) *ReceiveAddress {
	node, err := rauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rauo *ReceiveAddressUpdateOne) Exec(ctx context.Context) error {
	_, err := rauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rauo *ReceiveAddressUpdateOne) ExecX(ctx context.Context) {
	if err := rauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rauo *ReceiveAddressUpdateOne) defaults() {
	if _, ok := rauo.mutation.UpdatedAt(); !ok {
		v := receiveaddress.UpdateDefaultUpdatedAt()
		rauo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rauo *ReceiveAddressUpdateOne) check() error {
	if v, ok := rauo.mutation.Status(); ok {
		if err := receiveaddress.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReceiveAddress.status": %w`, err)}
		}
	}
	if v, ok := rauo.mutation.DeploymentTxHash(); ok {
		if err := receiveaddress.DeploymentTxHashValidator(v); err != nil {
			return &ValidationError{Name: "deployment_tx_hash", err: fmt.Errorf(`ent: validator failed for field "ReceiveAddress.deployment_tx_hash": %w`, err)}
		}
	}
	if v, ok := rauo.mutation.TxHash(); ok {
		if err := receiveaddress.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "ReceiveAddress.tx_hash": %w`, err)}
		}
	}
	return nil
}

func (rauo *ReceiveAddressUpdateOne) sqlSave(ctx context.Context) (_node *ReceiveAddress, err error) {
	if err := rauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(receiveaddress.Table, receiveaddress.Columns, sqlgraph.NewFieldSpec(receiveaddress.FieldID, field.TypeInt))
	id, ok := rauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReceiveAddress.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, receiveaddress.FieldID)
		for _, f := range fields {
			if !receiveaddress.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != receiveaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rauo.mutation.UpdatedAt(); ok {
		_spec.SetField(receiveaddress.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := rauo.mutation.Address(); ok {
		_spec.SetField(receiveaddress.FieldAddress, field.TypeString, value)
	}
	if value, ok := rauo.mutation.Salt(); ok {
		_spec.SetField(receiveaddress.FieldSalt, field.TypeBytes, value)
	}
	if rauo.mutation.SaltCleared() {
		_spec.ClearField(receiveaddress.FieldSalt, field.TypeBytes)
	}
	if value, ok := rauo.mutation.Status(); ok {
		_spec.SetField(receiveaddress.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := rauo.mutation.IsDeployed(); ok {
		_spec.SetField(receiveaddress.FieldIsDeployed, field.TypeBool, value)
	}
	if value, ok := rauo.mutation.DeploymentBlock(); ok {
		_spec.SetField(receiveaddress.FieldDeploymentBlock, field.TypeInt64, value)
	}
	if value, ok := rauo.mutation.AddedDeploymentBlock(); ok {
		_spec.AddField(receiveaddress.FieldDeploymentBlock, field.TypeInt64, value)
	}
	if rauo.mutation.DeploymentBlockCleared() {
		_spec.ClearField(receiveaddress.FieldDeploymentBlock, field.TypeInt64)
	}
	if value, ok := rauo.mutation.DeploymentTxHash(); ok {
		_spec.SetField(receiveaddress.FieldDeploymentTxHash, field.TypeString, value)
	}
	if rauo.mutation.DeploymentTxHashCleared() {
		_spec.ClearField(receiveaddress.FieldDeploymentTxHash, field.TypeString)
	}
	if value, ok := rauo.mutation.DeployedAt(); ok {
		_spec.SetField(receiveaddress.FieldDeployedAt, field.TypeTime, value)
	}
	if rauo.mutation.DeployedAtCleared() {
		_spec.ClearField(receiveaddress.FieldDeployedAt, field.TypeTime)
	}
	if value, ok := rauo.mutation.NetworkIdentifier(); ok {
		_spec.SetField(receiveaddress.FieldNetworkIdentifier, field.TypeString, value)
	}
	if rauo.mutation.NetworkIdentifierCleared() {
		_spec.ClearField(receiveaddress.FieldNetworkIdentifier, field.TypeString)
	}
	if value, ok := rauo.mutation.ChainID(); ok {
		_spec.SetField(receiveaddress.FieldChainID, field.TypeInt64, value)
	}
	if value, ok := rauo.mutation.AddedChainID(); ok {
		_spec.AddField(receiveaddress.FieldChainID, field.TypeInt64, value)
	}
	if rauo.mutation.ChainIDCleared() {
		_spec.ClearField(receiveaddress.FieldChainID, field.TypeInt64)
	}
	if value, ok := rauo.mutation.AssignedAt(); ok {
		_spec.SetField(receiveaddress.FieldAssignedAt, field.TypeTime, value)
	}
	if rauo.mutation.AssignedAtCleared() {
		_spec.ClearField(receiveaddress.FieldAssignedAt, field.TypeTime)
	}
	if value, ok := rauo.mutation.RecycledAt(); ok {
		_spec.SetField(receiveaddress.FieldRecycledAt, field.TypeTime, value)
	}
	if rauo.mutation.RecycledAtCleared() {
		_spec.ClearField(receiveaddress.FieldRecycledAt, field.TypeTime)
	}
	if value, ok := rauo.mutation.TimesUsed(); ok {
		_spec.SetField(receiveaddress.FieldTimesUsed, field.TypeInt, value)
	}
	if value, ok := rauo.mutation.AddedTimesUsed(); ok {
		_spec.AddField(receiveaddress.FieldTimesUsed, field.TypeInt, value)
	}
	if value, ok := rauo.mutation.LastIndexedBlock(); ok {
		_spec.SetField(receiveaddress.FieldLastIndexedBlock, field.TypeInt64, value)
	}
	if value, ok := rauo.mutation.AddedLastIndexedBlock(); ok {
		_spec.AddField(receiveaddress.FieldLastIndexedBlock, field.TypeInt64, value)
	}
	if rauo.mutation.LastIndexedBlockCleared() {
		_spec.ClearField(receiveaddress.FieldLastIndexedBlock, field.TypeInt64)
	}
	if value, ok := rauo.mutation.LastUsed(); ok {
		_spec.SetField(receiveaddress.FieldLastUsed, field.TypeTime, value)
	}
	if rauo.mutation.LastUsedCleared() {
		_spec.ClearField(receiveaddress.FieldLastUsed, field.TypeTime)
	}
	if value, ok := rauo.mutation.TxHash(); ok {
		_spec.SetField(receiveaddress.FieldTxHash, field.TypeString, value)
	}
	if rauo.mutation.TxHashCleared() {
		_spec.ClearField(receiveaddress.FieldTxHash, field.TypeString)
	}
	if value, ok := rauo.mutation.ValidUntil(); ok {
		_spec.SetField(receiveaddress.FieldValidUntil, field.TypeTime, value)
	}
	if rauo.mutation.ValidUntilCleared() {
		_spec.ClearField(receiveaddress.FieldValidUntil, field.TypeTime)
	}
	if rauo.mutation.PaymentOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   receiveaddress.PaymentOrderTable,
			Columns: []string{receiveaddress.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rauo.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   receiveaddress.PaymentOrderTable,
			Columns: []string{receiveaddress.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReceiveAddress{config: rauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{receiveaddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rauo.mutation.done = true
	return _node, nil
}
