// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/NEDA-LABS/stablenode/ent/paymentorder"
	"github.com/NEDA-LABS/stablenode/ent/receiveaddress"
	"github.com/google/uuid"
)

// ReceiveAddress is the model entity for the ReceiveAddress schema.
type ReceiveAddress struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Salt holds the value of the "salt" field.
	Salt []byte `json:"salt,omitempty"`
	// Status holds the value of the "status" field.
	Status receiveaddress.Status `json:"status,omitempty"`
	// Whether the smart account is deployed on-chain
	IsDeployed bool `json:"is_deployed,omitempty"`
	// Block number where account was deployed
	DeploymentBlock int64 `json:"deployment_block,omitempty"`
	// Transaction hash of deployment
	DeploymentTxHash string `json:"deployment_tx_hash,omitempty"`
	// Timestamp when deployed
	DeployedAt time.Time `json:"deployed_at,omitempty"`
	// Network identifier (e.g., base-sepolia)
	NetworkIdentifier string `json:"network_identifier,omitempty"`
	// Chain ID (e.g., 84532)
	ChainID int64 `json:"chain_id,omitempty"`
	// When address was assigned to an order
	AssignedAt time.Time `json:"assigned_at,omitempty"`
	// When address was returned to pool
	RecycledAt time.Time `json:"recycled_at,omitempty"`
	// Number of times address has been reused
	TimesUsed int `json:"times_used,omitempty"`
	// LastIndexedBlock holds the value of the "last_indexed_block" field.
	LastIndexedBlock int64 `json:"last_indexed_block,omitempty"`
	// LastUsed holds the value of the "last_used" field.
	LastUsed time.Time `json:"last_used,omitempty"`
	// TxHash holds the value of the "tx_hash" field.
	TxHash string `json:"tx_hash,omitempty"`
	// ValidUntil holds the value of the "valid_until" field.
	ValidUntil time.Time `json:"valid_until,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReceiveAddressQuery when eager-loading is set.
	Edges                         ReceiveAddressEdges `json:"edges"`
	payment_order_receive_address *uuid.UUID
	selectValues                  sql.SelectValues
}

// ReceiveAddressEdges holds the relations/edges for other nodes in the graph.
type ReceiveAddressEdges struct {
	// PaymentOrder holds the value of the payment_order edge.
	PaymentOrder *PaymentOrder `json:"payment_order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PaymentOrderOrErr returns the PaymentOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReceiveAddressEdges) PaymentOrderOrErr() (*PaymentOrder, error) {
	if e.PaymentOrder != nil {
		return e.PaymentOrder, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "payment_order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReceiveAddress) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case receiveaddress.FieldSalt:
			values[i] = new([]byte)
		case receiveaddress.FieldIsDeployed:
			values[i] = new(sql.NullBool)
		case receiveaddress.FieldID, receiveaddress.FieldDeploymentBlock, receiveaddress.FieldChainID, receiveaddress.FieldTimesUsed, receiveaddress.FieldLastIndexedBlock:
			values[i] = new(sql.NullInt64)
		case receiveaddress.FieldAddress, receiveaddress.FieldStatus, receiveaddress.FieldDeploymentTxHash, receiveaddress.FieldNetworkIdentifier, receiveaddress.FieldTxHash:
			values[i] = new(sql.NullString)
		case receiveaddress.FieldCreatedAt, receiveaddress.FieldUpdatedAt, receiveaddress.FieldDeployedAt, receiveaddress.FieldAssignedAt, receiveaddress.FieldRecycledAt, receiveaddress.FieldLastUsed, receiveaddress.FieldValidUntil:
			values[i] = new(sql.NullTime)
		case receiveaddress.ForeignKeys[0]: // payment_order_receive_address
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReceiveAddress fields.
func (ra *ReceiveAddress) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case receiveaddress.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ra.ID = int(value.Int64)
		case receiveaddress.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ra.CreatedAt = value.Time
			}
		case receiveaddress.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ra.UpdatedAt = value.Time
			}
		case receiveaddress.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				ra.Address = value.String
			}
		case receiveaddress.FieldSalt:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field salt", values[i])
			} else if value != nil {
				ra.Salt = *value
			}
		case receiveaddress.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ra.Status = receiveaddress.Status(value.String)
			}
		case receiveaddress.FieldIsDeployed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deployed", values[i])
			} else if value.Valid {
				ra.IsDeployed = value.Bool
			}
		case receiveaddress.FieldDeploymentBlock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deployment_block", values[i])
			} else if value.Valid {
				ra.DeploymentBlock = value.Int64
			}
		case receiveaddress.FieldDeploymentTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deployment_tx_hash", values[i])
			} else if value.Valid {
				ra.DeploymentTxHash = value.String
			}
		case receiveaddress.FieldDeployedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deployed_at", values[i])
			} else if value.Valid {
				ra.DeployedAt = value.Time
			}
		case receiveaddress.FieldNetworkIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network_identifier", values[i])
			} else if value.Valid {
				ra.NetworkIdentifier = value.String
			}
		case receiveaddress.FieldChainID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chain_id", values[i])
			} else if value.Valid {
				ra.ChainID = value.Int64
			}
		case receiveaddress.FieldAssignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_at", values[i])
			} else if value.Valid {
				ra.AssignedAt = value.Time
			}
		case receiveaddress.FieldRecycledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recycled_at", values[i])
			} else if value.Valid {
				ra.RecycledAt = value.Time
			}
		case receiveaddress.FieldTimesUsed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field times_used", values[i])
			} else if value.Valid {
				ra.TimesUsed = int(value.Int64)
			}
		case receiveaddress.FieldLastIndexedBlock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_indexed_block", values[i])
			} else if value.Valid {
				ra.LastIndexedBlock = value.Int64
			}
		case receiveaddress.FieldLastUsed:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used", values[i])
			} else if value.Valid {
				ra.LastUsed = value.Time
			}
		case receiveaddress.FieldTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tx_hash", values[i])
			} else if value.Valid {
				ra.TxHash = value.String
			}
		case receiveaddress.FieldValidUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_until", values[i])
			} else if value.Valid {
				ra.ValidUntil = value.Time
			}
		case receiveaddress.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_receive_address", values[i])
			} else if value.Valid {
				ra.payment_order_receive_address = new(uuid.UUID)
				*ra.payment_order_receive_address = *value.S.(*uuid.UUID)
			}
		default:
			ra.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReceiveAddress.
// This includes values selected through modifiers, order, etc.
func (ra *ReceiveAddress) Value(name string) (ent.Value, error) {
	return ra.selectValues.Get(name)
}

// QueryPaymentOrder queries the "payment_order" edge of the ReceiveAddress entity.
func (ra *ReceiveAddress) QueryPaymentOrder() *PaymentOrderQuery {
	return NewReceiveAddressClient(ra.config).QueryPaymentOrder(ra)
}

// Update returns a builder for updating this ReceiveAddress.
// Note that you need to call ReceiveAddress.Unwrap() before calling this method if this ReceiveAddress
// was returned from a transaction, and the transaction was committed or rolled back.
func (ra *ReceiveAddress) Update() *ReceiveAddressUpdateOne {
	return NewReceiveAddressClient(ra.config).UpdateOne(ra)
}

// Unwrap unwraps the ReceiveAddress entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ra *ReceiveAddress) Unwrap() *ReceiveAddress {
	_tx, ok := ra.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReceiveAddress is not a transactional entity")
	}
	ra.config.driver = _tx.drv
	return ra
}

// String implements the fmt.Stringer.
func (ra *ReceiveAddress) String() string {
	var builder strings.Builder
	builder.WriteString("ReceiveAddress(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ra.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ra.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ra.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(ra.Address)
	builder.WriteString(", ")
	builder.WriteString("salt=")
	builder.WriteString(fmt.Sprintf("%v", ra.Salt))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ra.Status))
	builder.WriteString(", ")
	builder.WriteString("is_deployed=")
	builder.WriteString(fmt.Sprintf("%v", ra.IsDeployed))
	builder.WriteString(", ")
	builder.WriteString("deployment_block=")
	builder.WriteString(fmt.Sprintf("%v", ra.DeploymentBlock))
	builder.WriteString(", ")
	builder.WriteString("deployment_tx_hash=")
	builder.WriteString(ra.DeploymentTxHash)
	builder.WriteString(", ")
	builder.WriteString("deployed_at=")
	builder.WriteString(ra.DeployedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("network_identifier=")
	builder.WriteString(ra.NetworkIdentifier)
	builder.WriteString(", ")
	builder.WriteString("chain_id=")
	builder.WriteString(fmt.Sprintf("%v", ra.ChainID))
	builder.WriteString(", ")
	builder.WriteString("assigned_at=")
	builder.WriteString(ra.AssignedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("recycled_at=")
	builder.WriteString(ra.RecycledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("times_used=")
	builder.WriteString(fmt.Sprintf("%v", ra.TimesUsed))
	builder.WriteString(", ")
	builder.WriteString("last_indexed_block=")
	builder.WriteString(fmt.Sprintf("%v", ra.LastIndexedBlock))
	builder.WriteString(", ")
	builder.WriteString("last_used=")
	builder.WriteString(ra.LastUsed.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tx_hash=")
	builder.WriteString(ra.TxHash)
	builder.WriteString(", ")
	builder.WriteString("valid_until=")
	builder.WriteString(ra.ValidUntil.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReceiveAddresses is a parsable slice of ReceiveAddress.
type ReceiveAddresses []*ReceiveAddress
